# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
commands:
    check_local:
        description: |
            Run Gitleaks against a local repository.
        parameters:
            options:
                default: ""
                description: Additional options to pass to the Gitleaks CLI.
                type: string
            path:
                default: ${CIRCLE_WORKING_DIRECTORY}
                description: Path to the local Git repository.
                type: string
        steps:
            - run:
                command: |
                    gitleaks --path=<< parameters.path >> << parameters.options >>
                name: Check repository for secrets
description: |
    Check Git repositories for secrets with Gitleaks. Source:
    https://github.com/upenn-libraries/circleci_orb_gitleaks
examples:
    check_local_repository_with_config_options:
        description: |
            Use Gitleaks to clone a remote repository and then check the local repository
            with the provided configuration options. This example will redact secrets
            from the build output, use the .gitleaks.toml file in the repository to
            configure Gitleaks, and use the provided Gitleaks Docker image.
        usage:
            orbs:
                gitleaks: upenn-libraries/gitleaks@0.1.0
                workflows:
                    check_for_secrets:
                        jobs:
                            - gitleaks/check_local:
                                image: quay.io/upennlibraries/gitleaks:v1.23.0
                                options: --redact --repo-config
            version: 2.1
    check_local_repository_with_default_config:
        description: |
            Use Gitleaks to clone a remote repository and then check the local repository
            with a default Gitleaks configuration.
        usage:
            orbs:
                gitleaks: upenn-libraries/gitleaks@0.1.0
                workflows:
                    check_for_secrets:
                        jobs:
                            - gitleaks/check_local
            version: 2.1
executors:
    docker:
        description: |
            Use a Gitleaks Docker container to check the repository for secrets.
        docker:
            - image: << parameters.image >>
        parameters:
            image:
                default: zricethezav/gitleaks
                description: |
                    The Gitleaks Docker image to use when checking a repository. It is
                    recommended that you publish your own image instead of trusting an image
                    that you don't control.
                type: string
jobs:
    check_local:
        description: |
            Clone a Git repository and check it for secrets.
        executor:
            image: << parameters.image >>
            name: docker
        parameters:
            image:
                default: zricethezav/gitleaks
                description: |
                    The Gitleaks Docker image to use when checking a repository. It is
                    recommended that you publish your own image instead of trusting an image
                    that you don't control.
                type: string
            options:
                default: ""
                description: Additional options to pass to the Gitleaks CLI.
                type: string
        steps:
            - checkout
            - check_local:
                options: << parameters.options >>
        working_directory: /root/project
version: 2.1

